// Generated by scripts/generate_schemas.py. DO NOT EDIT.
import { z } from "zod";

export const ClaimSchema = z
  .object({
  schemaVersion: z.literal(1),
  claimId: z.string().uuid(),
  jobId: z.string().uuid(),
  entityId: z.string().uuid(),
  subject: z.string().min(1).max(500),
  predicate: z.string().min(1).max(200),
  object: z.string().min(1).max(2000),
  displayText: z.string().min(1).max(3000),
  claimType: z.enum(["verified_fact", "company_claim", "third_party_report", "inference", "conflicted", "not_publicly_available"]),
  evidenceIds: z.array(z.string().uuid()).max(50),
  period: z.string().max(200).nullable().optional(),
  confidence: z.enum(["high", "medium", "low"]),
  freshness: z.enum(["current", "recent", "dated", "stale"]),
  contradictionGroup: z.string().uuid().nullable().optional(),
  verifierStatus: z.enum(["pending", "approved", "rejected", "conflicted"]),
  reportSections: z.array(z.string().min(1).max(100)).max(20),
  modelPromptVersion: z.string().min(1).max(100),
  isMaterial: z.boolean(),
  })
  .strict();
export type Claim = z.infer<typeof ClaimSchema>;

export const EntityCandidateEvidenceSnippetsItemSchema = z
  .object({
  evidenceId: z.string().uuid(),
  snippet: z.string().min(1).max(1000),
  sourceUrl: z.string().url(),
  companyControlled: z.boolean(),
  })
  .strict();
export type EntityCandidateEvidenceSnippetsItem = z.infer<typeof EntityCandidateEvidenceSnippetsItemSchema>;

export const EntityCandidateSchema = z
  .object({
  schemaVersion: z.literal(1),
  candidateId: z.string().uuid(),
  entityId: z.string().uuid().nullable().optional(),
  legalName: z.string().min(1).max(300),
  formerNames: z.array(z.string().min(1).max(300)).max(20).default([]),
  cin: z.string().regex(new RegExp("^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$")).nullable().optional(),
  companyType: z.enum(["private", "public_unlisted", "listed"]),
  listedStatus: z.enum(["listed", "unlisted"]).nullable().optional(),
  status: z.string().max(100).nullable().optional(),
  registeredOfficeState: z.string().max(100).nullable().optional(),
  registeredOfficeSummary: z.string().max(500).nullable().optional(),
  primaryDomain: z.string().regex(new RegExp("^(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\\\.)*[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")).max(253).nullable().optional(),
  brandNames: z.array(z.string().min(1).max(200)).max(20).default([]),
  confidenceScore: z.number().int().min(0).max(100),
  confidenceLabel: z.enum(["strong_match", "probable_match", "ambiguous", "insufficient_evidence"]),
  evidenceSnippets: z.array(EntityCandidateEvidenceSnippetsItemSchema).min(1).max(20),
  conflicts: z.array(z.string().min(1).max(500)).max(20),
  relatedEntityReason: z.string().max(500).nullable().optional(),
  })
  .strict();
export type EntityCandidate = z.infer<typeof EntityCandidateSchema>;

export const EvidenceEntityIdentifiersSchema = z
  .object({
  legalNames: z.array(z.string().min(1).max(300)).max(50),
  cins: z.array(z.string().regex(new RegExp("^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$"))).max(20),
  addresses: z.array(z.string().min(1).max(500)).max(20),
  })
  .strict();
export type EvidenceEntityIdentifiers = z.infer<typeof EvidenceEntityIdentifiersSchema>;

export const EvidenceSchema = z
  .object({
  schemaVersion: z.literal(1),
  evidenceId: z.string().uuid(),
  jobId: z.string().uuid(),
  entityId: z.string().uuid().nullable().optional(),
  url: z.string().url(),
  canonicalUrl: z.string().url(),
  title: z.string().min(1).max(500),
  publisher: z.string().min(1).max(300),
  sourceTier: z.number().int().min(1).max(5),
  publicationDate: z.string().date().nullable().optional(),
  accessedAt: z.string().datetime({ offset: true }),
  excerpt: z.string().min(1).max(4000),
  contentHash: z.string().regex(new RegExp("^[a-f0-9]{64}$")),
  entityIdentifiers: EvidenceEntityIdentifiersSchema,
  jurisdictionRelevance: z.string().max(500).nullable().optional(),
  companyControlled: z.boolean(),
  extractionMethod: z.enum(["static_html", "rendered", "api", "fixture"]),
  promptInjectionSuspected: z.boolean(),
  licenceNotes: z.string().max(500).nullable().optional(),
  rawBodyStorageKey: z.string().max(500).nullable().optional(),
  retentionClass: z.enum(["with_report", "raw_30d"]),
  })
  .strict();
export type Evidence = z.infer<typeof EvidenceSchema>;

export const JobMessageSchema = z
  .object({
  schemaVersion: z.literal(1),
  jobId: z.string().uuid(),
  reportRequestId: z.string().uuid(),
  userId: z.string().uuid(),
  confirmedEntityId: z.string().uuid(),
  attempt: z.number().int().min(1).max(100),
  traceId: z.string().min(8).max(128).regex(new RegExp("^[A-Za-z0-9._:-]+$")),
  budgetProfile: z.string().min(1).max(100),
  })
  .strict();
export type JobMessage = z.infer<typeof JobMessageSchema>;
