"""Entity-resolution website inspection boundary."""

from .candidates import (
    CandidateGenerationError,
    CandidateGenerationResult,
    CandidateGeneratorConfig,
    CandidateScoreAudit,
    CandidateSignalKind,
    EntityCandidateGenerator,
    EntityRelationshipHint,
    ResolutionGuidanceCode,
    ResolutionSignal,
    ScoringFactor,
    ScoringFacts,
    brand_context_statement,
    confidence_label,
    score_candidate,
)
from .crawler import CrawlerConfig, FetchClient, LegalPageCrawler
from .extraction import EXTRACTION_VERSION, extract_legal_page
from .models import (
    CrawlLimitation,
    DisclosureKind,
    ExtractionBasis,
    LegalDisclosure,
    LimitationCode,
    PageInspection,
    PageKind,
    RobotsStatus,
    SiteInspection,
)
from .task import (
    AsyncResolutionDatabase,
    EntityResolutionTaskHandler,
    PostgresResolutionRepository,
    ResolutionRepository,
    ResolutionRequest,
    ResolutionTaskError,
    build_entity_resolution_task_loop,
)

__all__ = [
    "EXTRACTION_VERSION",
    "AsyncResolutionDatabase",
    "CandidateGenerationError",
    "CandidateGenerationResult",
    "CandidateGeneratorConfig",
    "CandidateScoreAudit",
    "CandidateSignalKind",
    "CrawlLimitation",
    "CrawlerConfig",
    "DisclosureKind",
    "EntityCandidateGenerator",
    "EntityRelationshipHint",
    "EntityResolutionTaskHandler",
    "ExtractionBasis",
    "FetchClient",
    "LegalDisclosure",
    "LegalPageCrawler",
    "LimitationCode",
    "PageInspection",
    "PageKind",
    "PostgresResolutionRepository",
    "ResolutionGuidanceCode",
    "ResolutionRepository",
    "ResolutionRequest",
    "ResolutionSignal",
    "ResolutionTaskError",
    "RobotsStatus",
    "ScoringFactor",
    "ScoringFacts",
    "SiteInspection",
    "brand_context_statement",
    "build_entity_resolution_task_loop",
    "confidence_label",
    "extract_legal_page",
    "score_candidate",
]
