# Generated by scripts/generate_schemas.py. DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime
from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import AnyHttpUrl, BaseModel, ConfigDict, Field

class ClaimClaimType(StrEnum):
    VERIFIED_FACT = "verified_fact"
    COMPANY_CLAIM = "company_claim"
    THIRD_PARTY_REPORT = "third_party_report"
    INFERENCE = "inference"
    CONFLICTED = "conflicted"
    NOT_PUBLICLY_AVAILABLE = "not_publicly_available"

class ClaimConfidence(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"

class ClaimFreshness(StrEnum):
    CURRENT = "current"
    RECENT = "recent"
    DATED = "dated"
    STALE = "stale"

class ClaimVerifierStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    CONFLICTED = "conflicted"

class ClarificationSetQuestionsItemCode(StrEnum):
    CLIENT_ROLE = "client_role"
    TRANSACTION_CATEGORY = "transaction_category"
    CROSS_BORDER = "cross_border"
    KNOWN_PUBLIC_ISSUE = "known_public_issue"

class ClarificationSetQuestionsItemAnswerKind(StrEnum):
    SINGLE_SELECT = "single_select"
    OPTIONAL_SELECT = "optional_select"
    SHORT_TEXT = "short_text"

class ConfirmEntityRequestAction(StrEnum):
    CONFIRM = "confirm"
    NONE_OF_THESE = "none_of_these"
    REFINE = "refine"

class ConfirmEntityResponseState(StrEnum):
    DRAFT = "draft"
    RESOLVING_ENTITY = "resolving_entity"
    PRELIMINARY_RESEARCH = "preliminary_research"

class CreateReportRequestResponseReportRequestInputKind(StrEnum):
    WEBSITE = "website"
    LEGAL_NAME = "legal_name"

class CreateReportRequestInputKind(StrEnum):
    WEBSITE = "website"
    LEGAL_NAME = "legal_name"

class EntityCandidateCompanyType(StrEnum):
    PRIVATE = "private"
    PUBLIC_UNLISTED = "public_unlisted"
    LISTED = "listed"

class EntityCandidateListedStatus(StrEnum):
    LISTED = "listed"
    UNLISTED = "unlisted"

class EntityCandidateConfidenceLabel(StrEnum):
    STRONG_MATCH = "strong_match"
    PROBABLE_MATCH = "probable_match"
    AMBIGUOUS = "ambiguous"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"

class EvidenceExtractionMethod(StrEnum):
    STATIC_HTML = "static_html"
    RENDERED = "rendered"
    API = "api"
    FIXTURE = "fixture"

class EvidenceRetentionClass(StrEnum):
    WITH_REPORT = "with_report"
    RAW_30D = "raw_30d"

class LightTaskMessageTaskType(StrEnum):
    RESOLVE_ENTITY = "resolve_entity"
    PRELIMINARY_RESEARCH = "preliminary_research"
    RENDER_PDF = "render_pdf"

class Claim(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    claim_id: UUID = Field(..., alias="claimId")
    job_id: UUID = Field(..., alias="jobId")
    entity_id: UUID = Field(..., alias="entityId")
    subject: str = Field(..., min_length=1, max_length=500)
    predicate: str = Field(..., min_length=1, max_length=200)
    object: str = Field(..., min_length=1, max_length=2000)
    display_text: str = Field(..., alias="displayText", min_length=1, max_length=3000)
    claim_type: ClaimClaimType = Field(..., alias="claimType")
    evidence_ids: list[UUID] = Field(..., alias="evidenceIds", max_length=50)
    period: str | None = Field(default=None, max_length=200)
    confidence: ClaimConfidence = Field(...)
    freshness: ClaimFreshness = Field(...)
    contradiction_group: UUID | None = Field(default=None, alias="contradictionGroup")
    verifier_status: ClaimVerifierStatus = Field(..., alias="verifierStatus")
    report_sections: list[str] = Field(..., alias="reportSections", max_length=20)
    model_prompt_version: str = Field(..., alias="modelPromptVersion", min_length=1, max_length=100)
    is_material: bool = Field(..., alias="isMaterial")

class ClarificationSetQuestionsItem(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question_id: str = Field(..., alias="questionId", pattern="^[a-z0-9_:-]{3,100}$")
    code: ClarificationSetQuestionsItemCode = Field(...)
    prompt: str = Field(..., min_length=1, max_length=600)
    reason: str = Field(..., min_length=1, max_length=600)
    mandatory: bool = Field(...)
    answer_kind: ClarificationSetQuestionsItemAnswerKind = Field(..., alias="answerKind")
    answer_options: list[str] = Field(..., alias="answerOptions", max_length=6)
    confidentiality_safe: Literal[True] = Field(..., alias="confidentialitySafe")

class ClarificationSet(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    report_request_id: UUID = Field(..., alias="reportRequestId")
    entity_id: UUID = Field(..., alias="entityId")
    questions: list[ClarificationSetQuestionsItem] = Field(..., min_length=1, max_length=8)
    evidence_ids: list[UUID] = Field(..., alias="evidenceIds", max_length=20)
    sparse_data: bool = Field(..., alias="sparseData")
    planner_version: str = Field(..., alias="plannerVersion", pattern="^[A-Za-z0-9.-]{1,64}$")

class ConfirmEntityRequest(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    action: ConfirmEntityRequestAction = Field(...)
    candidate_id: UUID | None = Field(default=None, alias="candidateId")
    related_entity_ids: list[UUID] | None = Field(default_factory=list, alias="relatedEntityIds", max_length=2)
    legal_name: str | None = Field(default=None, alias="legalName", min_length=1, max_length=300)
    cin: str | None = Field(default=None, pattern="^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$")
    state: str | None = Field(default=None, min_length=1, max_length=100)

class ConfirmEntityResponse(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    state: ConfirmEntityResponseState = Field(...)
    confirmed_entity_id: UUID | None = Field(..., alias="confirmedEntityId")
    related_entity_ids: list[UUID] = Field(..., alias="relatedEntityIds", max_length=2)
    guidance: str | None = Field(..., max_length=500)

class CreateReportRequestResponseReportRequest(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: UUID = Field(...)
    input_kind: CreateReportRequestResponseReportRequestInputKind = Field(..., alias="inputKind")
    url: AnyHttpUrl | None = Field(..., max_length=2048)
    legal_name: str | None = Field(..., alias="legalName", max_length=300)
    cin: str | None = Field(..., pattern="^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$")
    confidential_ack_at: datetime = Field(..., alias="confidentialAckAt")
    state: Literal['draft'] = Field(...)
    created_at: datetime = Field(..., alias="createdAt")
    updated_at: datetime = Field(..., alias="updatedAt")

class CreateReportRequestResponse(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    report_request: CreateReportRequestResponseReportRequest = Field(..., alias="reportRequest")

class CreateReportRequest(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    input_kind: CreateReportRequestInputKind = Field(..., alias="inputKind")
    url: AnyHttpUrl | None = Field(default=None, min_length=1, max_length=2048)
    legal_name: str | None = Field(default=None, alias="legalName", min_length=1, max_length=300)
    cin: str | None = Field(default=None, pattern="^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$")
    confidential_ack: Literal[True] = Field(..., alias="confidentialAck")

class EntityCandidateEvidenceSnippetsItem(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    evidence_id: UUID = Field(..., alias="evidenceId")
    snippet: str = Field(..., min_length=1, max_length=1000)
    source_url: AnyHttpUrl = Field(..., alias="sourceUrl")
    company_controlled: bool = Field(..., alias="companyControlled")

class EntityCandidate(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    candidate_id: UUID = Field(..., alias="candidateId")
    entity_id: UUID | None = Field(default=None, alias="entityId")
    legal_name: str = Field(..., alias="legalName", min_length=1, max_length=300)
    former_names: list[str] | None = Field(default_factory=list, alias="formerNames", max_length=20)
    cin: str | None = Field(default=None, pattern="^[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$")
    company_type: EntityCandidateCompanyType = Field(..., alias="companyType")
    listed_status: EntityCandidateListedStatus | None = Field(default=None, alias="listedStatus")
    status: str | None = Field(default=None, max_length=100)
    registered_office_state: str | None = Field(default=None, alias="registeredOfficeState", max_length=100)
    registered_office_summary: str | None = Field(default=None, alias="registeredOfficeSummary", max_length=500)
    primary_domain: str | None = Field(default=None, alias="primaryDomain", pattern="^(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)*[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$", max_length=253)
    brand_names: list[str] | None = Field(default_factory=list, alias="brandNames", max_length=20)
    confidence_score: int = Field(..., alias="confidenceScore", ge=0, le=100)
    confidence_label: EntityCandidateConfidenceLabel = Field(..., alias="confidenceLabel")
    evidence_snippets: list[EntityCandidateEvidenceSnippetsItem] = Field(..., alias="evidenceSnippets", min_length=1, max_length=20)
    conflicts: list[str] = Field(..., max_length=20)
    related_entity_reason: str | None = Field(default=None, alias="relatedEntityReason", max_length=500)

class EvidenceEntityIdentifiers(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    legal_names: list[str] = Field(..., alias="legalNames", max_length=50)
    cins: list[str] = Field(..., max_length=20)
    addresses: list[str] = Field(..., max_length=20)

class Evidence(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    evidence_id: UUID = Field(..., alias="evidenceId")
    job_id: UUID = Field(..., alias="jobId")
    entity_id: UUID | None = Field(default=None, alias="entityId")
    url: AnyHttpUrl = Field(...)
    canonical_url: AnyHttpUrl = Field(..., alias="canonicalUrl")
    title: str = Field(..., min_length=1, max_length=500)
    publisher: str = Field(..., min_length=1, max_length=300)
    source_tier: int = Field(..., alias="sourceTier", ge=1, le=5)
    publication_date: date | None = Field(default=None, alias="publicationDate")
    accessed_at: datetime = Field(..., alias="accessedAt")
    excerpt: str = Field(..., min_length=1, max_length=4000)
    content_hash: str = Field(..., alias="contentHash", pattern="^[a-f0-9]{64}$")
    entity_identifiers: EvidenceEntityIdentifiers = Field(..., alias="entityIdentifiers")
    jurisdiction_relevance: str | None = Field(default=None, alias="jurisdictionRelevance", max_length=500)
    company_controlled: bool = Field(..., alias="companyControlled")
    extraction_method: EvidenceExtractionMethod = Field(..., alias="extractionMethod")
    prompt_injection_suspected: bool = Field(..., alias="promptInjectionSuspected")
    licence_notes: str | None = Field(default=None, alias="licenceNotes", max_length=500)
    raw_body_storage_key: str | None = Field(default=None, alias="rawBodyStorageKey", max_length=500)
    retention_class: EvidenceRetentionClass = Field(..., alias="retentionClass")

class JobMessage(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    job_id: UUID = Field(..., alias="jobId")
    report_request_id: UUID = Field(..., alias="reportRequestId")
    user_id: UUID = Field(..., alias="userId")
    confirmed_entity_id: UUID = Field(..., alias="confirmedEntityId")
    attempt: int = Field(..., ge=1, le=100)
    trace_id: str = Field(..., alias="traceId", min_length=8, max_length=128, pattern="^[A-Za-z0-9._:-]+$")
    budget_profile: str = Field(..., alias="budgetProfile", min_length=1, max_length=100)

class LightTaskMessage(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[1] = Field(..., alias="schemaVersion")
    task_id: UUID = Field(..., alias="taskId")
    task_type: LightTaskMessageTaskType = Field(..., alias="taskType")
    report_request_id: UUID = Field(..., alias="reportRequestId")
    user_id: UUID = Field(..., alias="userId")
    attempt: int = Field(..., ge=1, le=100)
    trace_id: str = Field(..., alias="traceId", min_length=8, max_length=128, pattern="^[A-Za-z0-9._:-]+$")

class ResolveEntityResponse(BaseModel):
    """Generated from the canonical Mandate JSON Schema."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    state: Literal['resolving_entity'] = Field(...)

__all__ = [
    "Claim",
    "ClaimClaimType",
    "ClaimConfidence",
    "ClaimFreshness",
    "ClaimVerifierStatus",
    "ClarificationSet",
    "ClarificationSetQuestionsItem",
    "ClarificationSetQuestionsItemAnswerKind",
    "ClarificationSetQuestionsItemCode",
    "ConfirmEntityRequest",
    "ConfirmEntityRequestAction",
    "ConfirmEntityResponse",
    "ConfirmEntityResponseState",
    "CreateReportRequest",
    "CreateReportRequestInputKind",
    "CreateReportRequestResponse",
    "CreateReportRequestResponseReportRequest",
    "CreateReportRequestResponseReportRequestInputKind",
    "EntityCandidate",
    "EntityCandidateCompanyType",
    "EntityCandidateConfidenceLabel",
    "EntityCandidateEvidenceSnippetsItem",
    "EntityCandidateListedStatus",
    "Evidence",
    "EvidenceEntityIdentifiers",
    "EvidenceExtractionMethod",
    "EvidenceRetentionClass",
    "JobMessage",
    "LightTaskMessage",
    "LightTaskMessageTaskType",
    "ResolveEntityResponse",
]
